name: blank

on:
  push:

jobs:
  dirt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        objection: ["suppose", "across", "bud", "blend", "honour"]
        scratch: ["literature", "optional", "hard", "outlook"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java -jar SU
